# Usage:
#   Production mode: docker compose up web
#   Development mode: docker compose up web-dev

services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      target: runner
    ports:
      - "3000:3000"

  web-dev:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ../services/web:/app
      - /app/node_modules
    stdin_open: true
    tty: true
